### ISSUE TITLE
Please explain what this is and how to use it

### ISSUE THREAD

**Issue by avioli** [Alicunde/HTML#2]
This project looks interesting, but I'm unsure how to use it.

What scripts or styles should I add to my page?
Is it only a Webpack-style bundle only?

Great work.

**Comment by salbatore** [comment]
Hi @avioli,

This system is not a library or framework. It is not intended to be imported in any way in any type of project. One of the motivations of the project was just that, to give absolute freedom to the programmer.

Therefore, you can find the source code of each component in the demo "code" tab, or in the folder of this same repository called components. CSS with inheritance and independent and HTML with a single class. So it is painless to copy and modify the components.

My intention is to create a base so that you can personalize the component yourself from the origin.

I'm glad you like it, it motivates me to continue improving the components. If you want to collaborate do not hesitate to write me.

😃
